project_id = "xqmrnfimcuktyyltikoy"

[functions.generate-training-images]
verify_jwt = false

[functions.apply-dno-rules]
verify_jwt = false

[functions.os-places-lookup]
verify_jwt = false

[functions.dno-capacity-lookup]
verify_jwt = false

[functions.ingest-geo-features]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.street-view-proxy]
verify_jwt = false

[functions.land-registry-lookup]
verify_jwt = false

[functions.land-registry-wms-proxy]
verify_jwt = false
