import WpOverviewTab from "./tabs/WpOverviewTab";
import WpSiteRegisterTab from "./tabs/WpSiteRegisterTab";
import WpMapTab from "./tabs/WpMapTab";
import WpEstimatingTab from "./tabs/WpEstimatingTab";
import WpPurchaseOrdersTab from "./tabs/WpPurchaseOrdersTab";
import WpVariationsTab from "./tabs/WpVariationsTab";
import WpGridStudiesTab from "./tabs/WpGridStudiesTab";
import WpDnoOffersTab from "./tabs/WpDnoOffersTab";
import WpDesignTab from "./tabs/WpDesignTab";
import WpProgrammeTab from "./tabs/WpProgrammeTab";
import WpTasksTab from "./tabs/WpTasksTab";
import WpPartnersTab from "./tabs/WpPartnersTab";
import WpPreConTab from "./tabs/WpPreConTab";
import WpReadinessTab from "./tabs/WpReadinessTab";
import WpDocumentsTab from "./tabs/WpDocumentsTab";
import WpPhotosTab from "./tabs/WpPhotosTab";
import WpAuditTab from "./tabs/WpAuditTab";
import WpCommissioningTab from "./tabs/WpCommissioningTab";

export const WpOverview = WpOverviewTab;
export const WpSiteRegister = WpSiteRegisterTab;
export const WpMap = WpMapTab;
export const WpPreCon = WpPreConTab;
export const WpReadiness = WpReadinessTab;
export const WpEstimating = WpEstimatingTab;
export const WpPurchaseOrders = WpPurchaseOrdersTab;
export const WpVariations = WpVariationsTab;
export const WpGridStudies = WpGridStudiesTab;
export const WpDnoOffers = WpDnoOffersTab;
export const WpDesign = WpDesignTab;
export const WpProgramme = WpProgrammeTab;
export const WpTasks = WpTasksTab;
export const WpPartners = WpPartnersTab;
export const WpDocuments = WpDocumentsTab;
export const WpPhotos = WpPhotosTab;
export const WpAudit = WpAuditTab;
export const WpCommissioning = WpCommissioningTab;