// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-my-sites.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_sites_default = defineTool({
  name: "list_my_sites",
  title: "List my sites",
  description: "List sites in the signed-in user's portfolio. Returns site name, postcode, coordinates, DNO, voltage and creation date. Scoped by the app's RLS policies.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50)."),
    search: z.string().optional().describe("Case-insensitive substring match on site name or postcode.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor(ctx);
    let q = supabase.from("sites").select("id, site_name, postcode, lat, lng, dno, voltage_level, proposed_kw, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search?.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`site_name.ilike.${s},postcode.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-studies.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_studies_default = defineTool2({
  name: "list_my_studies",
  title: "List my studies",
  description: "List Gridwise studies visible to the signed-in user (name, mode, status, DNO, voltage level, proposed kW, updated date).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows (default 50)."),
    status: z2.string().optional().describe("Optional exact status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = clientFor2(ctx).from("studies").select("id, study_name, mode, status, dno, voltage_level, proposed_kw, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status?.trim()) q = q.eq("status", status.trim());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { studies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-grid-assets.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function geocode(q) {
  const m = q.trim().match(/^(-?\d+(\.\d+)?)\s*,\s*(-?\d+(\.\d+)?)$/);
  if (m) return { lat: parseFloat(m[1]), lng: parseFloat(m[3]), label: q };
  const url = `https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=gb&q=${encodeURIComponent(q)}`;
  const r = await fetch(url, { headers: { "User-Agent": "gridwise-mcp/1.0" } });
  if (!r.ok) return null;
  const j = await r.json();
  if (!Array.isArray(j) || j.length === 0) return null;
  return { lat: parseFloat(j[0].lat), lng: parseFloat(j[0].lon), label: j[0].display_name };
}
var search_grid_assets_default = defineTool3({
  name: "search_grid_assets",
  title: "Search UK grid assets",
  description: "Find UK substations near a place, postcode or 'lat,lng'. Optionally filter by minimum headroom (kW), maximum utilisation (%), and local authority. Returns ranked results with distance.",
  inputSchema: {
    location: z3.string().describe("Place name, postcode, or 'lat,lng'."),
    radius_km: z3.number().min(0.1).max(100).optional().describe("Search radius in km (default 10)."),
    min_headroom_kw: z3.number().optional(),
    max_utilisation_pct: z3.number().optional(),
    local_authority: z3.string().optional(),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const loc = await geocode(args.location);
    if (!loc) {
      return {
        content: [{ type: "text", text: `Could not geocode "${args.location}".` }],
        isError: true
      };
    }
    const radius_m = Math.round((args.radius_km ?? 10) * 1e3);
    const max_rows = args.limit ?? 50;
    const { data, error } = await clientFor3(ctx).rpc("advisor_search_site_utilisation", {
      center_lng: loc.lng,
      center_lat: loc.lat,
      radius_m,
      min_headroom: args.min_headroom_kw ?? null,
      max_util: args.max_utilisation_pct ?? null,
      la: args.local_authority ?? null,
      max_rows
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = Array.isArray(data) ? data : [];
    return {
      content: [
        {
          type: "text",
          text: `Found ${results.length} substations near ${loc.label}.

${JSON.stringify(results, null, 2)}`
        }
      ],
      structuredContent: { resolved_location: loc, results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xqmrnfimcuktyyltikoy";
var mcp_default = defineMcp({
  name: "gridwise-connect-mcp",
  title: "Gridwise Connect",
  version: "0.1.0",
  instructions: "Tools for Gridwise Connect \u2014 a UK EV grid-connection intelligence platform. Use `search_grid_assets` to find substations near a location, `list_my_sites` for the signed-in user's portfolio sites, and `list_my_studies` for their saved studies. All data is scoped to the signed-in user by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_grid_assets_default, list_my_sites_default, list_my_studies_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
